apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai
  namespace: argocd
spec:
  description: "Project for managing ai resources"

  sourceRepos:
  - https://github.com/ray-project/kuberay
  - https://github.com/rmikl/argo-local.git

  destinations:
  - server: https://kubernetes.default.svc
    namespace: 'ai'
  - server: https://kubernetes.default.svc
    namespace: 'argocd'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
