apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sites
  namespace: argocd  
spec:
  description: "Project for managing sites resources"
  
  sourceRepos:
  - https://github.com/rmikl/helm_predeploy.git
  - https://github.com/rmikl/argo-local.git

  destinations:
  - server: https://kubernetes.default.svc
    namespace: 'sites'
  - server: https://kubernetes.default.svc
    namespace: 'argocd'

  clusterResourceWhitelist:
    - group: '*'  
      kind: '*'