apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: rayclusters.ray.io
  patch: |-
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
