apiVersion: v1
kind: ConfigMap
metadata:
  name: init-vnc
data:
  init.sh: |
    export DEBIAN_FRONTEND="noninteractive"
    sudo apt update
    sudo apt install software-properties-common apt-transport-https wget -y
    wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    sudo wget "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -O /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl
    sudo apt install code git -y
    cd /tmp
    wget https://www.keepersecurity.com/desktop_electron/Linux/repo/deb/keeperpasswordmanager_16.11.3_amd64.deb
    sudo dpkg -i keeperpasswordmanager_16.11.3_amd64.deb
    (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
    	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
      && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
      && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    	&& sudo apt update \
    	&& sudo apt install gh vim fzf -y
    sudo apt install zsh sshpass -y
    chsh -s $(which zsh)
    sudo sed -i 's|/bin/bash|/usr/bin/zsh|g' /etc/passwd

    sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
    echo "alias k=kubectl" >> ~/.zshrc
    echo "abc:$PASSWORD" | sudo chpasswd
    sudo chmod 777 /config/.zshrc
    sudo cat <<'EOF' >> ~/.zshrc
    ns() {
      local new_namespace="$1"
      if [ -z "$new_namespace" ]; then
        echo "Użycie: ns <namespace>"
        return 1
      fi
      sed -i 's|^alias k=.*|alias k="kubectl -n '"$new_namespace"'"|' ~/.zshrc
      echo "Zaktualizowano alias k na: kubectl -n $new_namespace"
      source ~/.zshrc
    }
    acp() {
      git add -A;git commit -m "$1";git push origin HEAD
    }
    aca() {
      git add -A;git commit --amend --no-edit ;git push origin HEAD --force
    }
    alias lapdell="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.33"
    alias lapmsi="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.36"
    alias lapsamsung="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.27"
    alias pc1="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.38"
    alias pc2="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.21"
    alias raspi44gb="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.40"
    alias raspi48gb="sshpass -p $LOCAL_NODES_PWD ssh -o  StrictHostKeyChecking=no robert@192.168.1.39"
    EOF
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions 
    source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
    sed -i 's|^plugins=(git)$|plugins=(git kubectl)|' /config/.zshrc
    git config --global user.name rmikl
    git config --global user.email robert.miklas@protonmail.com
    git config --global core.editor vim
---