apiVersion: v1
kind: Service
metadata:
  name: seba
  namespace: ingress-nginx
spec:
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: seba
  namespace: ingress-nginx
subsets:
- addresses:
  - ip: 192.168.1.48
  ports:
  - port: 8080
