apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miklas-psycholog
  namespace: argocd
spec:
  project: sites
  sources:
  - repoURL: https://github.com/rmikl/helm_predeploy.git
    targetRevision: HEAD
    path: custom-charts/chadcn-frontend-app
    helm:
      valueFiles:
      - $values/apps/sites/miklas-psycholog/values.yaml
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/sites/miklas-psycholog/additional-k8s-objects
  destination:
    server: https://kubernetes.default.svc
    namespace: sites
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
