# services.yaml
apiVersion: v1
kind: Service
metadata:
  name: wireguard-web
  namespace: wireguard
spec:
  type: ClusterIP
  ports:
  - name: http-ui
    port: 51821
    targetPort: 51821
    protocol: TCP
  selector:
    app: wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-vpn
  namespace: wireguard
spec:
  type: NodePort
  ports:
  - name: udp-vpn
    port: 51820
    targetPort: 51820
    protocol: UDP
    nodePort: 31820
  selector:
    app: wireguard