apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: llm-cluster
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true' # Required for head node
      metrics-export-port: '8080'
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-dell
        containers:
        - name: ray-head
          image: rayproject/ray:nightly-py311-cpu
          resources:
            limits:
              cpu: "10"
              memory: "28Gi"
  workerGroupSpecs:
  - groupName: samsung-group # Required unique identifier
    rayStartParams:
      # Required for workers
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-msi
        containers:
        - name: ray-worker
          image: rayproject/ray:nightly-py311-cpu
          resources:
            limits:
              cpu: "7"
              memory: "12Gi"
  - groupName: pc1-group # Required unique identifier
    rayStartParams:
      # Required for workers
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: pc-1
        containers:
        - name: ray-worker
          image: rayproject/ray:nightly-py311-cpu
          resources:
            limits:
              cpu: "3"
              memory: "12Gi"
