apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: llm-cluster
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-dell # Head node on lap-dell
        containers:
        - name: ray-head
          image: rayproject/ray:nightly-py311-cpu
          resources:
            limits:
              cpu: "2" # Adjusted for shared node
              memory: "8Gi" # Adjusted for shared node

  workerGroupSpecs:
  - groupName: dell-worker-group
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
      resources: '"lap-dell-node=1"' # Add this
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-dell
        containers:
        - name: ray-worker
          env:
          - name: RAY_OVERRIDE_RESOURCES
            value: '"lap-dell-node=1"' # Add this
          - name: RAY_RESOURCES
            value: '"lap-dell-node=1"'
          image: rmikl/ray-nightly-py311-cpu:78ad3b475db611c0501ad0bc4feb60987b4cbddb
          ports:
          - containerPort: 8000 # Expose the HTTP port
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: "7"
              memory: "18Gi"

  # Existing worker groups
  - groupName: msi-group
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-msi
        containers:
        - name: ray-worker
          image: rayproject/ray:nightly-py311-cpu
          resources:
            limits:
              cpu: "7"
              memory: "12Gi"
            requests:
              cpu: "7"
              memory: "12Gi"

  - groupName: pc1-group
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: pc-1
        containers:
        - name: ray-worker
          image: rayproject/ray:nightly-py311-cpu
          resources:
            limits:
              cpu: "3"
              memory: "12Gi"
            requests:
              cpu: "3"
              memory: "12Gi"
