apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: llm-cluster
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-dell # Head node on lap-dell
        containers:
        - name: ray-head
          image: rmikl/ray-nightly-py311-cpu:53eacfa90336c0524e38d0a236eb9337efff2e74
          resources:
            limits:
              cpu: "2" 
              memory: "8Gi" 

  workerGroupSpecs:
  - groupName: dell-worker
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
      resources: '"{\"lap-dell-node\": 1}"' #Add this
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-dell
        containers:
        - name: ray-worker
          env:
          - name: RAY_RESOURCES
            value: '{"lap-dell-node": 1}'
          image: rayproject/ray:2.42.1-py311-cpu
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: "5"
              memory: "16Gi"
          volumeMounts:
          - name: repos
            mountPath: /repos
        volumes:
        - name: repos
          persistentVolumeClaim:
            claimName: repos




  # Existing worker groups
  - groupName: msi-group
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: lap-msi
        containers:
        - name: ray-worker
          image: rayproject/ray:2.42.1-py311-cpu
          resources:
            limits:
              cpu: "7"
              memory: "12Gi"
            requests:
              cpu: "7"
              memory: "12Gi"

  - groupName: pc1-group
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: 'true'
      metrics-export-port: '8080'
    replicas: 1
    template:
      spec:
        nodeSelector:
          kubernetes.io/hostname: pc-1
        containers:
        - name: ray-worker
          image: rayproject/ray:2.42.1-py311-cpu
          resources:
            limits:
              cpu: "3"
              memory: "12Gi"
            requests:
              cpu: "3"
              memory: "12Gi"
