apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd # Argo CD manages this Application
spec:
  project: infra
  sources:
  - chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.8
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/metallb/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: metallb.io
    kind: IPAddressPool
    jqPathExpressions:
    - .spec.addresses
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
