apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
spec:
  project: infra
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io/
    targetRevision: 0.14.0
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/external-secrets/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
