apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd  
spec:
  project: infra
  sources:
  - chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx 
    targetRevision: 4.12.0
    helm:
      valueFiles: 
      - $values/apps/infra/values/nginx-ingress.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc  
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true