apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat
  namespace: argocd
spec:
  project: media
  sources:
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/media/chat/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
