apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: infra
spec:
  refreshInterval: 1h  # Optional: How often to refresh the secret from the external store (e.g., every hour)
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: grafana-admin-password
    remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
      property: password  # Optional: Specify if the secret has nested properties (e.g., a JSON object with a "password" field)
    conversionStrategy: Default  # Ensures the secret is handled in its default format (no transformation needed)
    decodingStrategy: None  # No decoding needed if the secret is stored as plain text; use "Base64" if encoded
    metadataPolicy: None  # No metadata handling; use "Merge" or "Replace" if needed for annotations/labels
  - secretKey: grafana-admin-user
    remoteRef:
      key: GRAFANA_ADMIN_USER
      property: username  # Optional: Specify if the secret has nested properties (e.g., a JSON object with a "username" field)
    conversionStrategy: Default
    decodingStrategy: None
    metadataPolicy: None
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner  # Ensures the secret is created/owned by this ExternalSecret resource