apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: infra
spec:
  refreshInterval: 1h  # Optional: How often to refresh the secret from the external store
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: grafana-admin-password
    remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
      property: password  # Remove if your secret is a simple key-value pair
  - secretKey: grafana-admin-user
    remoteRef:
      key: GRAFANA_ADMIN_USER
      property: username  # Remove if your secret is a simple key-value pair
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner  # Ensures the secret is created/owned by this ExternalSecret