apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: grafana-admin-password
    remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: grafana-admin-user
    remoteRef:
      key: GRAFANA_ADMIN_USER
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner