apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: infra
  resourceVersion: "5515615"  # Optional: Include if required by your setup
  uid: d84d2503-7f3e-4aa8-af17-14d7927ca297  # Optional: Include if required
spec:
  refreshInterval: 1h  # Optional: How often to refresh the secret from the external store
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: grafana-admin-password
    remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
  - secretKey: grafana-admin-user
    remoteRef:
      key: GRAFANA_ADMIN_USER
  target:
    name: grafana-admin-credentials