apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.15.3
    helm:
      valueFiles:
      - $values/apps/infra/cert-manager/values.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/cert-manager/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
    jqPathExpressions:
    - '.webhooks[] | select(.name == "webhook.cert-manager.io") | .namespaceSelector.matchExpressions'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
