apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: infra
  sources:
  - chart: node-feature-discovery
    repoURL: https://kubernetes-sigs.github.io/node-feature-discovery
    targetRevision: v0.17.1
    helm:
      valueFiles:
      - $values/apps/infra/node-feature-discovery/values.yaml
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
