apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: admin_password
    remoteRef:
      key: VNC_PASSWORD
  - secretKey: admin_email
    remoteRef:
      key: OPENWEBUI_ACCESS_USERNAME_EMAIL
  - secretKey: secret_key
    remoteRef:
      key: OPENWEBUI_ACCESS_KEY
  target:
    name: openwebui-access
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bedrock-api-gateway-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: access_key
    remoteRef:
      key: AWS_ACCESS_KEY
  - secretKey: secret_key
    remoteRef:
      key: AWS_SECRET_KEY
  target:
    name: aws-secret
---