apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avertbhp
  namespace: argocd
spec:
  project: sites
  sources:
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/sites/avertbhp/additional-k8s-objects
  destination:
    server: https://kubernetes.default.svc
    namespace: sites
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
