apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd 
spec:
  project: infra
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.15.3  
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-operators
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
    jqPathExpressions:
    - '.webhooks[] | select(.name == "webhook.cert-manager.io") | .namespaceSelector.matchExpressions'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
