apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd 
spec:
  project: infra
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    chart: csi-driver-smb
    targetRevision: 1.16.0
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true