apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd  
spec:
  project: infra
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io/
    targetRevision: 0.11.0
  destination:
    server: https://kubernetes.default.svc  
    namespace: cluster-operators
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true