apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: infra
spec:
  project: infra
  sources:
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/ingress-nginx/ingress-nginx.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
