apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-operators
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: ingress-nginx
  template:
    metadata:
      name: '{{name}}'
      namespace: infra
    spec:
      project: infra
      source:
        repoURL: https://github.com/rmikl/argo-local.git
        targetRevision: HEAD
        path: apps/infra/{{name}}/
      destination:
        server: https://kubernetes.default.svc
        namespace: 'infra'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
