apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd  
spec:
  project: infra
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts  # The Helm repository URL for Istio
    chart: istiod  # The Helm chart name
    targetRevision: 1.23.3  # The chart version
    helm:
      valueFiles:
      - $values/apps/infra/values/istiod.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc  
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jqPathExpressions:
    - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane" or .key == "kubernetes.azure.com/managedby")
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
