apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd  
spec:
  project: infra
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts  
    targetRevision: 1.23.0  
#  - chart: gateway
#    repoURL: https://istio-release.storage.googleapis.com/charts  
#    targetRevision: 1.23.0  
#    helm:
#      valueFiles: 
#      - $values/apps/infra/values/istio-ingress-values.yaml
#  - repoURL: https://github.com/rmikl/argo-cd
#    targetRevision: HEAD
#    ref: values
  destination:
    server: https://kubernetes.default.svc  
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
