apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd  
spec:
  project: infra
  sources:
  - chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts  
    targetRevision: 1.23.2
    helm:
      valueFiles: 
      - $values/apps/infra/values/istio-ingress-values.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc  
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
