apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://github.com/jellyfin/jellyfin-helm.git
    targetRevision: master
    path: charts/jellyfin
    helm:
      valueFiles:
      - $values/apps/infra/values/jellyfin.yaml
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true