apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metallb/metallb.yaml
- ingress-nginx/ingress-nginx.yaml
- reflector/reflector.yaml
- metrics-server/metrics-server.yaml
- update-ext-ip/update-ext-ip.yaml
- external-secrets/external-secrets.yaml
- cert-manager/cert-manager.yaml
- external-dns/external-dns.yaml
- argo-ingress/argo-ingress.yaml
- csi-driver-samba/csi-driver-samba.yaml
- nvidia-gpu-operator/nvidia-gpu-operator.yaml
