apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://nextcloud.github.io/helm
    chart: nextcloud
    targetRevision: 6.1.0
  #  helm:
  #    valueFiles:
  #    - $values/apps/infra/values/nextcloud.yaml
  #- repoURL: https://github.com/rmikl/argo-local.git
  #  targetRevision: HEAD
  #  ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true