apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: owncloud
    targetRevision: 12.2.11
    helm:
      valueFiles:
      - $values/apps/infra/values/owncloud.yaml
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true