apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
spec:
  project: infra
  sources:
  - chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v24.6.2
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-operators
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
