apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator-crds
  namespace: argocd
spec:
  project: ai
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: v1.2.2
    path: helm-chart/kuberay-operator/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true # Delete resources when they are not in Git
      selfHeal: true # Automatically sync when actual state deviates from target state
      allowEmpty: false
    syncOptions:
    - Replace=true
