apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay
  namespace: argocd
spec:
  project: ai
  sources:
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/ai/kuberay/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
