apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay
  namespace: argocd
spec:
  project: ai
  sources:
  - repoURL: https://ray-project.github.io/kuberay-helm/
    targetRevision: 1.2.2
    chart: kuberay-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Add resource customization section
  resourceCustomizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      rayservices.ray.io:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
      rayjobs.ray.io:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
      rayclusters.ray.io:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
