apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay
  namespace: argocd
spec:
  project: ai
  sources:
  - repoURL: https://ray-project.github.io/kuberay-helm/
    targetRevision: 1.2.2
    chart: kuberay/kuberay-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
