apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-plugins
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/device-plugins/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
