apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: cloudflare_api_token
    remoteRef:
      key: CF_API_TOKEN
  target:
    name: external-dns
    #template:
    #  metadata:
    #    annotations:
    #      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    #      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sites,media"
    #      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
