apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sites
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
---