apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: avertbhp:apps/Deployment:sites/avertbhp
  name: avertbhp
  namespace: sites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avertbhp
  template:
    metadata:
      labels:
        app: avertbhp
    spec:
      containers:
      - env:
        - name: GITPULLER_REPO_URL
          value: https://github.com/rmikl/frontapp_card.git
        - name: GITPULLER_BRANCH
          value: avert     # Zmieniono z "master" na "avert"
        - name: GITPULLER_REPO_PATH
          value: /app/repo
        - name: SLEEP_TIME
          value: "10"
        image: rmikl/github_puller:1.0.627
        imagePullPolicy: IfNotPresent
        name: git-sync
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: git-volume
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: git-volume
          subPath: repo
        command:
        - /bin/sh
        - -c
        - |
          # Tworzenie tymczasowej konfiguracji
          mkdir -p /tmp/nginx/conf.d
          cat > /tmp/nginx/nginx.conf <<EOF
          user  nginx;
          worker_processes  auto;
          error_log  /var/log/nginx/error.log notice;
          pid        /tmp/nginx.pid;
          events {
              worker_connections  1024;
          }
          http {
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;
              log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                             '\$status \$body_bytes_sent "\$http_referer" '
                             '"\$http_user_agent" "\$http_x_forwarded_for"';
              access_log  /var/log/nginx/access.log  main;
              sendfile        on;
              keepalive_timeout  65;
              server {
                  listen       80;
                  server_name  _;
                  location / {
                      root   /usr/share/nginx/html;
                      index  index.html index.htm;
                      try_files \$uri \$uri/ /index.html;
                  }
                  error_page   500 502 503 504  /50x.html;
                  location = /50x.html {
                      root   /usr/share/nginx/html;
                  }
              }
          }
          EOF
          # Uruchomienie Nginx z niestandardową konfiguracją
          nginx -c /tmp/nginx/nginx.conf -g "daemon off;"
      volumes:
      - emptyDir: {}
        name: git-volume