apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler
  data:
  - secretKey: cloudflare_api_token
    remoteRef:
      key: CF_API_TOKEN
  target:
    name: external-dns
    template:
      templateFrom:
      - target: Annotations
        literal: |
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sites,media"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qnap-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler
  data:
  - secretKey: username
    remoteRef:
      key: SMB_USERNAME
  - secretKey: password
    remoteRef:
      key: SMB_PASSWORD
  target:
    name: qnap-credentials
    template:
      templateFrom:
      - target: Annotations
        literal: |
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sites,media"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
---

