apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler
  namespace: infra
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
