apiVersion: v1
kind: Service
metadata:
  name: openvpn-service
  namespace: infra
  labels:
    app: openvpn
spec:
  type: NodePort
  selector:
    app: openvpn
  ports:
    - name: admin
      port: 943
      targetPort: 943
      nodePort: 30943
      protocol: TCP       
    - name: vpn-udp
      port: 1194
      targetPort: 926  # Zmień z 1194 na 926
      nodePort: 31194
      protocol: UDP