apiVersion: v1
kind: Service
metadata:
  name: openvpn-service
  namespace: infra
  labels:
    app: openvpn
spec:
  type: ClusterIP
  selector:
    app: openvpn
  ports:
  - name: admin
    port: 943
    targetPort: 943
    protocol: TCP
  - name: vpn-tcp
    port: 1194
    targetPort: 1194
    protocol: TCP