apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qnap-credentials
  namespace: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: username
    remoteRef:
      key: SMB_USERNAME # Verify this key exists in Doppler
  - secretKey: password
    remoteRef:
      key: SMB_PASSWORD # Verify this key exists in Doppler
  target:
    name: qnap-credentials
    #template:
    #  metadata:
    #    annotations:
    #      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    #      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sites,media"
    #      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
