apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-vpn
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/open-vpn/k8s-manifests/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true