apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: update-ext-ip
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://github.com/rmikl/helm_predeploy.git
    targetRevision: master
    path: custom-charts/kubectl-update-ext-ip
    helm:
      valueFiles:
      - $values/apps/infra/update-ext-ip/values.yaml
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
