apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd # Argo CD manages this Application
spec:
  syncPolicy:
    automated:
      prune: true # Automatically delete removed resources
      selfHeal: true # Automatically correct state drift
    syncOptions:
    - CreateNamespace=true # Optional: Create namespace if missing
  project: infra
  sources:
  - chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      valueFiles:
      - $values/apps/infra/ingress-nginx/values.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  #add only when you want to add additional k8s objects
  #- repoURL: https://github.com/rmikl/argo-local.git
  #  targetRevision: HEAD
  #  path: apps/infra/ingress-nginx/k8s-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
