apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd # Argo CD manages this Application
spec:
  project: infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    chart: ingress-nginx
    helm:
      valueFiles:
      - $values/apps/infra/ingress-nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra # Where the Ingress Controller deploys
