controller:
  config:
    allowSnippetAnnotations: true
  replicaCount: 1
  service:
    enableHttps: true
    targetPorts:
      https: 443
      http: 80
    externalTrafficPolicy: Cluster
    type: LoadBalancer
    # Add OpenVPN port to LoadBalancer service
    ports:
      http: 80
      https: 443
      openvpn: 1194  # Add OpenVPN port
  # Enable TCP streams support
  extraArgs:
    tcp-services-configmap: "$(POD_NAMESPACE)/tcp-services"
  # Add OpenVPN port to container
  containerPorts:
    - name: http
      containerPort: 80
      protocol: TCP
    - name: https  
      containerPort: 443
      protocol: TCP
    - name: openvpn
      containerPort: 1194
      protocol: TCP

# TCP services configuration
tcp:
  1194: "infra/openvpn-service:1194"  # Point to future OpenVPN service

allowSnippetAnnotations: true
rbac:
  create: true
serviceAccount:
  create: true