controller:
  config:
    allowSnippetAnnotations: true
  replicaCount: 1
  service:
    enableHttps: true
    targetPorts:
      https: 443
      http: 80
    externalTrafficPolicy: Cluster
    type: LoadBalancer
    # Add OpenVPN port to LoadBalancer service
    ports:
      http: 80
      https: 443
  # Enable TCP streams support
  containerPorts:
    - name: http
      containerPort: 80
      protocol: TCP
    - name: https  
      containerPort: 443
      protocol: TCP



allowSnippetAnnotations: true
rbac:
  create: true
serviceAccount:
  create: true