controller:
  allowSnippetAnnotations: true
  replicaCount: 1
  service:
    enableHttps: true
    targetPorts:
      https: 443
      http: 80
    externalTrafficPolicy: Cluster
    type: LoadBalancer
  extraArgs:
    enable-snippet-annotations: "true"
rbac:
  create: true
serviceAccount:
  create: true


