apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: infra
      - name: media
      - name: sites
      - name: ai
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: '{{name}}'
      source:
        repoURL: https://github.com/rmikl/argo-local.git
        targetRevision: HEAD
        path: 'apps/{{name}}'
        kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: argoproj.io
        kind: Application
        name: '{{name}}'
        jsonPointers:
        - /spec/source/kustomize
