apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: grafana-admin-password
    remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
  - secretKey: grafana-admin-user
    remoteRef:
      key: GRAFANA_ADMIN_USER
  target:
    name: grafana-admin-credentials