apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-comunity
    targetRevision: 69.4.1
    helm:
      valueFiles:
      - $values/apps/infra/kube-prometheus/values.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true