apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.4.1
    helm:
      valueFiles:
      - $values/apps/infra/kube-prometheus/values.yaml
  - repoURL: https://github.com/rmikl/argo-local
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/rmikl/argo-local.git
    targetRevision: HEAD
    path: apps/infra/kube-prometheus/k8s-manifests/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - /spec/data/0/conversionStrategy
    - /spec/data/0/decodingStrategy
    - /spec/data/0/metadataPolicy
    - /spec/data/1/conversionStrategy
    - /spec/data/1/decodingStrategy
    - /spec/data/1/metadataPolicy