provider: cloudflare

domainFilters:
- rmikl.pl
- miklas-psycholog.pl
- avertbhp.pl

namespaced: false

sources:
- ingress

policy: sync
registry: txt

rbac:
  create: true
  serviceAccountName: external-dns

livenesProbe:
  enabled: false

#im overwriting this image version according to:
#https://github.com/kubernetes-sigs/external-dns/issues/5035
image:
  tag: 0.14.2
