apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector-operator
  namespace: argocd
spec:
  destination:
    namespace: cluster-operators
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: 7.1.288
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
