apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: torrent-auth
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
  - secretKey: auth
    remoteRef:
      key: INGRESS_BASIC_AUTH
  target:
    name: torrent-auth
