secretStore:
  name: doppler-auth-api
  doppler:
    dopplerTokenSecretName: doppler-token-auth-api
    dopplerTokenKey: dopplerToken

externalSecret:
  name: cloudflare-api
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  targetSecretName: cloudflare-api
  data:
  - secretKey: apiToken
    remoteRefKey: CF_API_TOKEN
  - secretKey: apiKey
    remoteRefKey: CF_API_KEY
  - secretKey: email
    remoteRefKey: CF_EMAIL
  