secretStore:
  name: doppler-auth-api
  doppler:
    dopplerTokenSecretName: doppler-token-auth-api
    dopplerTokenKey: dopplerToken

externalSecret:
  name: cloudflare-api-key
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  targetSecretName: cloudflare-api-key
  data:
    - secretKey: CF_API_TOKEN
      remoteRefKey: CF_API_TOKEN