provider: cloudflare

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-api
      key: apiToken
- name: CF_API_KEY
  valueFrom:
    secretKeyRef:
      name: cloudflare-api
      key: apiKey
- name: CF_API_EMAIL
  valueFrom:
    secretKeyRef:
      name: cloudflare-api
      key: email


domainFilters:
  - rmikl.pl

namespaced: false

sources:
- istio-gateway

policy: sync
registry: txt

rbac:
  create: true
  serviceAccountName: external-dns