replicas: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.cluster-operators.svc.cluster.local

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: "default"
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-persistent-volumes:
      gnetId: 13646
      revision: 1
      datasource: Prometheus
    1_K8S_for_Prometheus_Dashboard_20211010_EN:
      gnetId: 15661
      revision: 1
      datasource: Prometheus
      name: k3
    Storage I/O Statistics:
      gnetId: 11801
      revision: 1
      datasource: Prometheus
    K8s Cluster Metrics:
      gnetId: 11663
      revision: 1
      datasource: Prometheus
    Kubernetes Monitor:
      gnetId: 15398
      revision: 1
      datasource: Prometheus
    Network Traffic:
      gnetId: 12619
      revision: 1
      datasource: Prometheus
    Kubernetes monitoring by namespace and instance:
      gnetId: 15826
      revision: 1
      datasource: Prometheus
    Kubernetes / Networking / Pod Flows (Workload):
      gnetId: 20929
      revision: 1
      datasource: Prometheus


    
