replicas: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

admin:
  existingSecret: grafana-admin-credentials 
  userKey: admin-user                        
  passwordKey: admin-password                

persistence:
  enabled: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.cluster-operators.svc.cluster.local
        access: proxy
        isDefault: true