replicas: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.cluster-operators.svc.cluster.local

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: "default"
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes:
      gnetId: 13332
      revision: 1
      datasource: Prometheus
    kube-state-metrics-v2:
      gnetId: 13332
      revision: 1
      datasource: Prometheus
    K8S-for-Prometheus-Dashboard:
      gnetId: 15661
      revision: 1
      datasource: Prometheus
    cert-manager:
      gnetId: 11001
      revision: 1
      datasource: Prometheus
    K8s_Storage_Volumes_Cluster:
      gnetId: 11454
      revision: 1
      datasource: Prometheus
    Kubernetes_cluster_monitoring:
      gnetId: 315
      revision: 1
      datasource: Prometheus
    Kubernetes_cluster:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus