ingress:
  enabled: false

persistence: 
  media:
    enabled: true
    accessMode: ReadWriteMany
    size: 100Gi            # Increased size as needed
    storageClass: dlink
  config:
    enabled: false        # Disable separate config PVC

service:
  type: NodePort   
  port: 80         
  nodePort: 32080

replicaCount: 1

image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

# Add these sections
extraVolumeMounts:
  - name: media
    mountPath: /media
  - name: media
    mountPath: /config
    subPath: k8s-tools-config/jellyfin_config

extraVolumes:
  - name: media
    persistentVolumeClaim:
      claimName: jellyfin-media 