ingress:
  enabled: false

persistence:
  media:
    enabled: false            # Disable automatic creation of media PVC
  config:
    enabled: false     

service:
  type: NodePort   
  port: 80         
  nodePort: 32080

replicaCount: 1

image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi


extraVolumeMounts:
  - name: media
    mountPath: /media
  - name: media
    mountPath: /config
    subPath: k8s-tools-config/jellyfin_config

extraVolumes:
  - name: media
    persistentVolumeClaim:
      claimName: dlink