ingress:
  enabled: false

persistence:
  media:
    enabled: true
    existingClaim: dlink
  config:
    enabled: true
    existingClaim: dlink
    subPath: k8s-tools-config/jellyfin_config
 
service:
  type: NodePort   
  port: 80         
  nodePort: 32080

replicaCount: 1

image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi
