image:
  repository: nextcloud
  flavor: apache
  tag: stable-apache
  pullPolicy: IfNotPresent

replicaCount: 1

nextcloud:
  host: ncloud.rmikl.pl
  #persistence:
  #  subPathPrefix: "k8s-tools-config/nexcloud_config"
  #  subPath: ""

  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

internalDatabase:
  enabled: true
  name: nextcloud

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClass: "dlink-db" 
  accessMode: ReadWriteMany 
  subPath: "nextcloud"
  size: 8Gi

externalDatabase:
  existingSecret: 
    secretName: nextcloud-credentials
    usernameKey: mariadb-user
    passwordKey: mariadb-password 

mariadb:
  enabled: true
  auth:
    existingSecret: nextcloud-credentials
    usernameKey: username
    passwordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: "dlink-db"
      accessMode: ReadWriteOnce
      size: 8Gi
      subPath: nextcloud_config/mariadb
  
rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

redis:
  enabled: true
  auth:
    existingSecret: nextcloud-credentials
    usernameKey: username
    passwordKey: password
  global:
    storageClass: "dlink-db"
  master:
    persistence:
      enabled: true
      storageClass: "dlink-db"
  replica: 
    enabled: false

configs:
  php-custom.ini: |-
    opcache.enable=1
    opcache.enable_cli=1
    opcache.memory_consumption=128
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.validate_timestamps=1
    opcache.revalidate_freq=60
    memory_limit=512M
    realpath_cache_size=4096K
    realpath_cache_ttl=600
    apc.enable_cli=1
    apc.shm_size=64M
    upload_max_filesize=16G
    post_max_size=16G
    session.gc_maxlifetime=1440
    session.cookie_lifetime=0