image:
  repository: nextcloud
  flavor: apache
  tag: stable-apache
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: false

nextcloud:
  host: nextcloud.rmikl.pl
  username: admin
  password: changeme
  existingSecret:
    enabled: true
    secretName: nextcloud
    usernameKey: username
    passwordKey: password
  update: 0

  containerPort: 80
  datadir: /var/www/html/data
  persistence:
    subPath: "k8s-tools-config/nextcloud_config/data"  

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1
#
  #extraVolumes:
  #  - name: db-volume
  #    persistentVolumeClaim:
  #      claimName: nextcloud-nextcloud
#
  #extraVolumeMounts:
  #  - name: db-volume
  #    mountPath: /var/lib/mysql
  #    subPath: k8s-tools-config/nextcloud_config/db

internalDatabase:
  enabled: true
  name: nextcloud

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  annotations: {}
  storageClass: "dlink" 
  accessMode: ReadWriteMany  
  size: 8Gi
  nextcloudData:
    enabled: true
    subPath: "k8s-tools-config/nextcloud_config/data"
    annotations: {}
    accessMode: ReadWriteMany
    size: 8Gi  

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
