image:
  repository: nextcloud
  flavor: apache
  tag: stable-apache
  pullPolicy: IfNotPresent

replicaCount: 0

ingress:
  enabled: false

nextcloud:
  host: nextcloud.rmikl.pl
  existingSecret:
    enabled: true
    secretName: nextcloud
    usernameKey: username
    passwordKey: password
  update: 0
  containerPort: 80
  datadir: /var/www/html/data

internalDatabase:
  enabled: true
  name: nextcloud

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClassName: "dlink" 
  accessMode: ReadWriteMany  
  size: 8Gi
  nextcloudData:
    enabled: true
    subPath: "k8s-tools-config/nextcloud_config/data"
    accessMode: ReadWriteMany
    size: 8Gi  

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
