image:
  repository: nextcloud
  flavor: apache
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 0

ingress:
  enabled: false

nextcloud:
  host: nextcloud.rmikl.pl
  username: admin
  password: changeme
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: username
    passwordKey: password
  update: 0
  
  containerPort: 80
  datadir: /var/www/html/data
  persistence:
    subPath: "k8s-tools-config/nextcloud_config/data"  

  extraVolumes:
    - name: config-volume
      persistentVolumeClaim:
        claimName: nextcloud-pvc
    - name: db-volume
      persistentVolumeClaim:
        claimName: nextcloud-pvc

  extraVolumeMounts:
    - name: config-volume
      mountPath: /var/www/html/config
      subPath: k8s-tools-config/nextcloud_config/config
    - name: db-volume
      mountPath: /var/lib/mysql
      subPath: k8s-tools-config/nextcloud_config/db

internalDatabase:
  enabled: true
  name: nextcloud

service:
  type: ClusterIP
  port: 8080
  loadBalancerIP: ""
  nodePort: null
  annotations: {}

persistence:
  enabled: true
  annotations: {}
  storageClass: "dlink" 
  accessMode: ReadWriteMany  
  size: 8Gi
  nextcloudData:
    enabled: false
    subPath: "k8s-tools-config/nextcloud_config/config"
    annotations: {}
    accessMode: ReadWriteMany
    size: 8Gi  

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
