#nextcloud:
#  persistance:
#    enabled: true
#    storageClass: "dlink-ssd"
#    size: "10Gi"
#    accessMode: "ReadWriteMany"

persistence:
  enabled: true
  storageClass: "dlink-ssd" 
  accessMode: ReadWriteMany 
  size: 8Gi
  nextcloudData: 
    enabled: true
    storageClass: "dlink-ssd"
    accessMode: ReadWriteMany
    size: 8Gi

readinessProbe:
  enabled: false

livenessProbe:
  enabled: false

