image:
  repository: nextcloud
  flavor: apache
  tag: stable-apache
  pullPolicy: IfNotPresent

replicaCount: 1

nextcloud:
  host: ncloud.rmikl.pl
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

internalDatabase:
  enabled: true
  name: nextcloud

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClassName: "dlink" 
  accessMode: ReadWriteMany  
  size: 8Gi

mariadb:
  enabled: true
  auth:
    existingSecret: nextcloud-credentials
    usernameKey: username
    passwordKey: password
  
rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
