image:
  repository: nextcloud
  flavor: apache
  tag: stable-apache
  pullPolicy: IfNotPresent

replicaCount: 1

nextcloud:
  host: ncloud.rmikl.pl
  persistence:
    subPathPrefix: "k8s-tools-config/nexcloud_config"
    subPath: ""

  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

internalDatabase:
  enabled: true
  name: nextcloud

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClass: "dlink-ncloud" 
  accessMode: ReadWriteMany 
  subPath: k8s-tools-config/nexcloud_config 
  size: 8Gi
  nextcloudData: 
    enabled: true
    storageClass: "dlink-ncloud"
    accessMode: ReadWriteMany
    size: 8Gi
    subPath: ""

externalDatabase:
  existingSecret: 
    secretName: nextcloud-credentials
    usernameKey: mariadb-user
    passwordKey: mariadb-password 

mariadb:
  enabled: true
  auth:
    existingSecret: nextcloud-credentials
    usernameKey: username
    passwordKey: password
  primary:
    persistence:
      enabled: true
      storageClass: "dlink"
      accessMode: ReadWriteOnce
      size: 8Gi
      subPath: k8s-tools-config/nexcloud_config/mariadb
  
rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false

securityContext:
 # runAsUser: 33
 # runAsGroup: 33
  fsGroup: 33
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
