
replicaCount: 0

owncloudHost: oc.rmikl.pl
owncloudUsername: admin
existingSecret: nextcloud
allowEmptyPassword: false

mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: bitnami_owncloud
    username: bn_owncloud
  primary:
    persistence:
      enabled: true
      storageClass: "dlink"
      accessModes:
        - ReadWriteOnce
      hostPath: "k8s-tools-config/owncloud_config/db"

persistence:
  enabled: true
  storageClass: dlink
  accessModes:
    - ReadWriteMany
  size: 8Gi
  hostPath: "k8s-tools-config/owncloud_data/data"

service:
  type: ClusterIP
  ports:
    http: 8080
 