replicaCount: 1

owncloud:
  domain: ocloud.rmikl.pl
  username: owncloud
  password: owncloud

mariadb:
  enabled: false

externalDatabase:
  type: ""
  host: ""
  port: 3306
  name: owncloud
  user: owncloud
  password: owncloud

persistence:
  enabled: true
  storageClassName: dlink-ssd
  owncloud:
    accessMode: ReadWriteMany
    size: 8Gi

redis:
  enabled: false

image:
  repository: docker.io/owncloud/server
  pullPolicy: IfNotPresent
  tag: 10.6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: 
  fsGroup: 33 
  enabled: true

securityContext:
  enabled: true 
  runAsUser: 0    # Use the UID of the application user
  runAsGroup: 0
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv:
  - name: OWNCLOUD_USERNAME
    valueFrom:
      secretKeyRef:
        name: owncloud-credentials
        key: db-username
  - name: OWNCLOUD_PASSWORD
    valueFrom:
      secretKeyRef:
        name: owncloud-credentials
        key: owncloud-password
