alertmanager:
  enabled: true
  persistentVolume:
    enabled: false 

server:
  global:
    scrape_interval: 30s 
  resources:
    limits:
      cpu: 1000m 
      memory: 1500Mi 
    requests:
      cpu: 500m
      memory: 1000Mi  
  retention: 36h 
  persistentVolume:
    enabled: false 
  nodeSelector: {}  
  tolerations: []  