apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vnc
  name: vnc
  namespace: media
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vnc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vnc
    spec:
      nodeSelector:
        kubernetes.io/hostname: lap-dell
      terminationGracePeriodSeconds: 30
      containers:
      - image: rmikl/vnc_server:797481e2e6ac2fc9fadd5e10eddc4dbb6c0d6b6d
        name: vnc-http
        command:
        - /bin/bash
        - -c
        - |
          /vnc-script/init.sh
          /init
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                PROCESSESS_TO_KILL="$(pgrep firefox) $(pgrep code)"
                if [ -n "$PROCESSESS_TO_KILL" ]; then
                  kill -9 $PROCESSESS_TO_KILL
                fi
        securityContext:
          capabilities:
            add: ["SYS_RESOURCE"]
        env:
        - name: DRINODE
          value: /dev/dri/renderD128
        - name: CUSTOM_USER
          value: rmikl
        - name: USER
          value: rmikl
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: VNC_PASSWORD
              name: vnc-credentials
        - name: GITHUB_TOKEN_RAW
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN_RAW
              name: vnc-credentials
        - name: LOCAL_NODES_PWD
          valueFrom:
            secretKeyRef:
              key: LOCAL_NODES_PWD
              name: vnc-credentials
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            gpu.intel.com/i915: "1"
            cpu: "2"
            memory: "8Gi"            
          requests:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /vnc-script
          name: vnc-init
        - mountPath: /kube
          name: secret-volume
        - mountPath: /mnt/qnap
          name: vnc-base
        - name: containerd-sock
          mountPath: /run/containerd
        - name: vnc-rc
          mountPath: /init-config
        - name: vnc-mozilla
          mountPath: /config/.mozilla
        - name: vnc-vscode
          mountPath: /config/.vscode
      volumes:
      - name: vnc-base
        persistentVolumeClaim:
          claimName: vnc-base
      - name: vnc-mozilla
        persistentVolumeClaim:
          claimName: vnc-mozilla
      - name: vnc-vscode
        persistentVolumeClaim:
          claimName: vnc-vscode
      - name: vnc-init
        configMap:
          name: vnc-config-files
          items:
          - key: init.sh
            path: init.sh
          defaultMode: 0777  
      - name: vnc-rc 
        configMap:
          name: vnc-config-files
          items:
          - key: .zshrc
            path: .zshrc
          - key: .gitconfig
            path: .gitconfig
          defaultMode: 0777 
      - name: secret-volume
        secret:
          defaultMode: 420
          items:
          - key: KUBECONFIG
            path: config
          secretName: vnc-credentials
      - name: containerd-sock
        hostPath:
          path: /run/containerd
          type: Directory