apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vnc
  name: vnc
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vnc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vnc
    spec:
      securityContext:
        sysctls:
          #- name: fs.inotify.max_user_instances
          #  value: "1024"
          #- name: fs.inotify.max_user_watches
          #  value: "524288"
      nodeSelector:
        kubernetes.io/hostname: lap-dell
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          #mkdir -p /run/dbus
          rm -rf /config/.config/Code/User /config/.XDG
          #dbus-daemon --system --fork
          /vnc-script/init.sh
          /init
        securityContext:
          capabilities:
            runAsUser: 0
            add: ["SYS_RESOURCE"]
        env:
        - name: DRINODE
          value: /dev/dri/renderD128
        - name: CUSTOM_USER
          value: rmikl
        - name: USER
          value: rmikl
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: VNC_PASSWORD
              name: vnc-credentials
        - name: GITHUB_TOKEN_RAW
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN_RAW
              name: vnc-credentials
        - name: LOCAL_NODES_PWD
          valueFrom:
            secretKeyRef:
              key: LOCAL_NODES_PWD
              name: vnc-credentials
        image: rmikl/vnc_server:1.0.718
        name: vnc-http
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            gpu.intel.com/i915: "1"
        volumeMounts:
        - mountPath: /config
          name: home-data
        - mountPath: /vnc-script  # Fixed: Matches volume name "vnc-init"
          name: vnc-init
        - mountPath: /kube
          name: secret-volume
        - mountPath: /mnt/qnap
          name: vnc-base
        - name: containerd-sock
          mountPath: /run/containerd
        - name: vnc-rc
          mountPath: /init-config
      volumes:
      - name: vnc-base
        persistentVolumeClaim:
          claimName: vnc-base
      - name: home-data
        persistentVolumeClaim:
          claimName: vnc-home
      - name: vnc-init  # Volume index 2: Fixed configMap reference
        configMap:
          name: vnc-config-files
          items:
          - key: init.sh
            path: init.sh
          defaultMode: 0777  # Octal format
      - name: vnc-rc  # Volume index 3: Fixed configMap reference
        configMap:
          name: vnc-config-files
          items:
          - key: .zshrc
            path: .zshrc
          - key: .gitconfig
            path: .gitconfig
          defaultMode: 0777  # Octal format
      - name: secret-volume
        secret:
          defaultMode: 420
          items:
          - key: KUBECONFIG
            path: config
          secretName: vnc-credentials
      - name: containerd-sock
        hostPath:
          path: /run/containerd
          type: Directory