apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "vnc"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  name: vnc
  namespace: media
spec:
  ingressClassName: nginx
  rules:
  - host: vnc.rmikl.pl
    http:
      paths:
      - backend:
          service:
            name: vnc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - vnc.rmikl.pl
    secretName: rmikl.pl
---