apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vnc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: qnap
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vnc-mozilla
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: qnap
  resources:
    requests:
      storage: 1Gi
  volumeAttributes:
    source: "//192.168.1.48/smb/k8s-tools-config/vnc"
    subDir: ".mozilla"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vnc-vscode
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: qnap
  resources:
    requests:
      storage: 1Gi
  volumeAttributes:
    source: "//192.168.1.48/smb/k8s-tools-config/vnc"
    subDir: ".vscode"
