# Storage Class for .mozilla
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-mozilla
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.48/smb/k8s-tools-config/vnc/.mozilla"
  csi.storage.k8s.io/node-stage-secret-name: qnap-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: infra
  csi.storage.k8s.io/node-publish-secret-name: qnap-credentials
  csi.storage.k8s.io/node-publish-secret-namespace: infra
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
- vers=3.0
- rsize=1048576
- wsize=1048576
- cache=strict
- nobrl
- dir_mode=0777
- file_mode=0777
- mfsymlinks
- noserverino
---
# Storage Class for .vscode
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-vscode
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.48/smb/k8s-tools-config/vnc/.vscode"
  csi.storage.k8s.io/node-stage-secret-name: qnap-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: infra
  csi.storage.k8s.io/node-publish-secret-name: qnap-credentials
  csi.storage.k8s.io/node-publish-secret-namespace: infra
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
- vers=3.0
- rsize=1048576
- wsize=1048576
- cache=strict
- nobrl
- dir_mode=0777
- file_mode=0777
- mfsymlinks
- noserverino
---
# Storage Class for .vscode
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-home
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.48/smb/k8s-tools-config/vnc/home"
  csi.storage.k8s.io/node-stage-secret-name: qnap-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: infra
  csi.storage.k8s.io/node-publish-secret-name: qnap-credentials
  csi.storage.k8s.io/node-publish-secret-namespace: infra
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
- vers=3.0
- rsize=1048576
- wsize=1048576
- cache=strict
- nobrl
- dir_mode=0777
- file_mode=0777
- mfsymlinks
- noserverino
---

